title: Maak een GameObject dat draait
hero_image: images/banner.png
description: Maak een GameObject dat draait
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Maak een GameObject dat draait
