title: Create a GameObject that spins
hero_image: images/banner.png
description: Create a GameObject that spins
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Create a GameObject that spins
